blueprint:
  name: TRV06 Universal Heizlogik – Final Perfect 2025
  description: >
    Perfekte Heizlogik für TRV06 Thermostate:
    - Hysterese Tag & Nacht
    - Einstellbare Zeiten
    - Fenstererkennung
    - Master EIN/AUS-Schalter
    - Temperatur = 5°C bevor OFF (echtes Abschalten)
    - Sicher gegen unknown/unavailable
    - Debug optional

  domain: automation

  input:

    climate:
      name: Thermostat
      selector:
        entity:
          domain: climate

    tempsensor:
      name: Raumtemperatur-Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    door_or_window:
      name: Tür-/Fenstersensor
      selector:
        entity:
          domain: binary_sensor

    heating_enabled:
      name: Heizlogik EIN/AUS
      selector:
        entity:
          domain: input_boolean

    day_time:
      name: Start TAG
      default: "08:00:00"
      selector:
        time: {}

    night_time:
      name: Start NACHT
      default: "22:00:00"
      selector:
        time: {}

    day_temp:
      name: Tag Solltemperatur
      default: 23
      selector:
        number:
          min: 5
          max: 30
          step: 0.1

    night_temp:
      name: Nacht Solltemperatur
      default: 18
      selector:
        number:
          min: 5
          max: 30
          step: 0.1

    low_temp_threshold_day:
      name: Tag – Einschalten unter
      default: 19.9
      selector:
        number:
          min: 5
          max: 30
          step: 0.1

    high_temp_threshold_day:
      name: Tag – Ausschalten über
      default: 22.1
      selector:
        number:
          min: 5
          max: 30
          step: 0.1

    low_temp_threshold_night:
      name: Nacht – Einschalten unter
      default: 17.7
      selector:
        number:
          min: 5
          max: 30
          step: 0.1

    high_temp_threshold_night:
      name: Nacht – Ausschalten über
      default: 18.2
      selector:
        number:
          min: 5
          max: 30
          step: 0.1

    door_window_delay:
      name: Fensterverzögerung (Sekunden)
      default: 60
      selector:
        number:
          min: 0
          max: 300
          step: 1

    debug:
      name: Debug aktivieren
      default: false
      selector:
        boolean: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: homeassistant
    event: start
    id: start
  - platform: event
    event_type: homeassistant_started
    id: start2
  - platform: state
    entity_id: !input tempsensor
  - platform: state
    entity_id: !input door_or_window
  - platform: state
    entity_id: !input heating_enabled
  - platform: time
    at: !input day_time
  - platform: time
    at: !input night_time

variables:
  climate_entity: !input climate
  temp_entity: !input tempsensor
  window_entity: !input door_or_window
  heating_sw: !input heating_enabled

  daytemp: !input day_temp
  nighttemp: !input night_temp

  low_day: !input low_temp_threshold_day
  high_day: !input high_temp_threshold_day
  low_night: !input low_temp_threshold_night
  high_night: !input high_temp_threshold_night

  window_delay: !input door_window_delay
  debug_log: !input debug

  day_start: !input day_time
  night_start: !input night_time
  nowtime: "{{ now().strftime('%H:%M:%S') }}"

  # Sicher gegen unknown/unavailable
  room_temp: >
    {% if states(temp_entity) in ['unknown','unavailable','None','nan'] %}
      999
    {% else %}
      {{ states(temp_entity) | float }}
    {% endif %}

  window_open: "{{ is_state(window_entity, 'on') }}"

  daytime: "{{ day_start <= nowtime < night_start }}"
  nighttime: "{{ nowtime >= night_start or nowtime < day_start }}"

action:

  # Startverzögerung
  - choose:
      - conditions: "{{ trigger.id in ['start','start2'] }}"
        sequence:
          - delay: "00:03:00"

  # Debug
  - choose:
      - conditions: "{{ debug_log }}"
        sequence:
          - service: logbook.log
            data:
              name: "TRV06 Heizlogik"
              message: >
                Temp={{ room_temp }}°C,
                Fenster={{ window_open }},
                Heizlogik={{ states(heating_sw) }},
                Modus={{ 'Tag' if daytime else 'Nacht' }}
              entity_id: "{{ climate_entity }}"

  # Heizlogik AUS → Temperatur = 5° → OFF
  - choose:
      - conditions:
          - condition: state
            entity_id: !input heating_enabled
            state: "off"
        sequence:
          - service: climate.set_temperature
            data:
              temperature: 5
            target:
              entity_id: "{{ climate_entity }}"

          - delay: "00:00:02"

          - service: climate.turn_off
            target:
              entity_id: "{{ climate_entity }}"

          - stop: "Heizlogik deaktiviert"

  # Fenster offen → 5° → OFF
  - choose:
      - conditions: "{{ window_open }}"
        sequence:
          - delay:
              seconds: "{{ window_delay }}"

          - condition: template
            value_template: "{{ is_state(window_entity, 'on') }}"

          - service: climate.set_temperature
            data:
              temperature: 5
            target:
              entity_id: "{{ climate_entity }}"

          - delay: "00:00:02"

          - service: climate.turn_off
            target:
              entity_id: "{{ climate_entity }}"

          - stop: "Fenster offen → AUS"

  # Solltemperatur setzen (immer vor Hysterese)
  - choose:
      - conditions: "{{ daytime }}"
        sequence:
          - service: climate.set_temperature
            data:
              temperature: "{{ daytemp }}"
            target:
              entity_id: "{{ climate_entity }}"

      - conditions: "{{ nighttime }}"
        sequence:
          - service: climate.set_temperature
            data:
              temperature: "{{ nighttemp }}"
            target:
              entity_id: "{{ climate_entity }}"

  # Hysterese
  - choose:

      # TAG
      - conditions: "{{ daytime }}"
        sequence:

          # EIN
          - choose:
              - conditions: "{{ room_temp < low_day }}"
                sequence:
                  - service: climate.turn_on
                    target:
                      entity_id: "{{ climate_entity }}"

          # AUS (mit 5° setzen!)
          - choose:
              - conditions: "{{ room_temp > high_day }}"
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: 5
                    target:
                      entity_id: "{{ climate_entity }}"

                  - delay: "00:00:02"

                  - service: climate.turn_off
                    target:
                      entity_id: "{{ climate_entity }}"

      # NACHT
      - conditions: "{{ nighttime }}"
        sequence:

          # EIN
          - choose:
              - conditions: "{{ room_temp < low_night }}"
                sequence:
                  - service: climate.turn_on
                    target:
                      entity_id: "{{ climate_entity }}"

          # AUS mit 5°
          - choose:
              - conditions: "{{ room_temp > high_night }}"
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: 5
                    target:
                      entity_id: "{{ climate_entity }}"

                  - delay: "00:00:02"

                  - service: climate.turn_off
                    target:
                      entity_id: "{{ climate_entity }}"
